language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - cpanm -n --quiet --installdeps --with-develop .
after_success:
  - cover -test -report coveralls
sudo: false
notifications:
  email: false
