language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm --quiet --installdeps .
  - cpanm -n Devel::Cover::Report::Coveralls
install:
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
