language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - cpanm --quiet --installdeps --with-develop .
script:
  - perl Makefile.PL && make && make test && cover -test -report coveralls
sudo: false
notifications:
  email: false
